# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 988d563e299cb3c4563d018e4528a02b6c0bdf29d01ecf231d76f181c90bfb2ae832b5927dd78ec50508a640132ff38fd0b44a307f684aad73bf4e31953df256

test:
  secret_key_base: d2058357da66950395513865ac5793904fd7e90b63ad4c18248037447f81695af7fd829966ce8245e727eeda0917b1e5f3d7bfb0b62e2a4b7a77cdfe2b55e5da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
